DROP TABLE IF EXISTS EVENT_HIGHLIGHTS;
DROP TABLE IF EXISTS EVENT_LEARNINGS;
DROP TABLE IF EXISTS EVENT_SCHEDULE;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS REGISTRATIONS;

CREATE TABLE EVENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  status VARCHAR(50),
  date VARCHAR(100),
  time VARCHAR(100),
  location VARCHAR(255),
  organizer VARCHAR(255),
  fee VARCHAR(50),
  image VARCHAR(255),
  description VARCHAR(1000)
);

CREATE TABLE EVENT_HIGHLIGHTS (
  event_id INT,
  highlights VARCHAR(255)
);

CREATE TABLE EVENT_LEARNINGS (
  event_id INT,
  learnings VARCHAR(255)
);

CREATE TABLE EVENT_SCHEDULE (
  event_id INT,
  schedule VARCHAR(255)
);

CREATE TABLE REGISTRATIONS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  registration_id VARCHAR(50),
  event_id INT,
  username VARCHAR(255),
  email VARCHAR(255),
  mobile VARCHAR(20),
  college VARCHAR(255),
  department VARCHAR(100),
  study_year VARCHAR(20),
  payment_option VARCHAR(50),
  payment_proof VARCHAR(255),
  reg_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);